From Sulfur Require Import Prelude Sig Renamings.

(** This file defines a term grammar parameterized over a signature,
    with _admissible_ renamings and substitutions i.e. renamings
    are functions [nat -> nat] and substitutions are functions [nat -> term].

    We prove the main properties of substitution and renaming. *)

Section WithSignature.
Context {sig : signature}.

(*********************************************************************************)
(** *** Parameterized syntax. *)
(*********************************************************************************)

(** Notations for expressions with known kinds. *)
#[local] Reserved Notation "'term'" (at level 0).
#[local] Reserved Notation "'arg' ty" (at level 1, ty at level 1).
#[local] Reserved Notation "'args' tys" (at level 1, tys at level 1).

Unset Elimination Schemes.

(** Terms over an abstract signature.
    Terms are indexed by a kind. *)
Inductive expr : kind -> Type :=
| (** Term variable. *)
  E_var : nat -> term
| (** Non-variable expr constructor, applied to a list of arguments. *)
  E_ctor : forall c, args (ctor_type c) -> term
| (** Empty argument list. *)
  E_al_nil : args []
| (** Non-empty argument list. *)
  E_al_cons {ty tys} : arg ty -> args tys -> args (ty :: tys)
| (** Base argument (e.g. bool or string). *)
  E_abase : forall b, eval_base b -> arg (AT_base b)
| (** Term argument. *)
  E_aterm : term -> arg AT_term
| (** Bind a term in an argument. *)
  E_abind {ty} : arg ty -> arg (AT_bind ty)

where "'term'" := (expr Kt)
  and "'arg' ty" := (expr (Ka ty))
  and "'args' tys" := (expr (Kal tys)).

Set Elimination Schemes.

Derive Signature for expr.

(** Due to the nested occurence of [vec] in [expr], the induction principle
    automatically generated by Rocq is too weak. We prove a stronger one. *)

Section ExprInd.
  Context (P : forall k, expr k -> Prop).

  Context (H_var : forall i, P _ (E_var i)).
  Context (H_ctor : forall c al, P _ al -> P _ (E_ctor c al)).
  Context (H_al_nil : P _ E_al_nil).
  Context (H_al_cons : forall ty tys (a : arg ty) (al : args tys),
    P _ a -> P _ al -> P _ (E_al_cons a al)).
  Context (H_abase : forall b x, P _ (E_abase b x)).
  Context (H_aterm : forall t, P _ t -> P _ (E_aterm t)).
  Context (H_abind : forall ty (a : arg ty), P _ a -> P _ (E_abind a)).

  Fixpoint expr_ind k (t : expr k) {struct t} : P k t.
  Proof.
  destruct t.
  - apply H_var.
  - apply H_ctor. apply expr_ind.
  - apply H_al_nil.
  - apply H_al_cons ; apply expr_ind.
  - apply H_abase.
  - apply H_aterm. apply expr_ind.
  - apply H_abind. apply expr_ind.
  Qed.

End ExprInd.

Register Scheme expr_ind as ind_dep for expr.

(*********************************************************************************)
(** *** Size of expressions. *)
(*********************************************************************************)

(** Size of an expression. This is used in the plugin to prove a custom
    induction principle for concrete syntax. *)
Equations esize {k} (t : expr k) : nat by struct t :=
esize (E_var _) := 0 ;
esize (E_ctor c al) := S (esize al) ;
esize E_al_nil := 0 ;
esize (E_al_cons a al) := S (esize a + esize al) ;
esize (E_abase _ _) := 0 ;
esize (E_aterm t) := S (esize t) ;
esize (E_abind a) := S (esize a).

(*********************************************************************************)
(** *** Inversion lemmas. *)
(*********************************************************************************)

(** In order to avoid using [depelim] in the plugin (which can be quite slow),
    we prove simple inversion lemmas which we then use in the plugin when
    generating the custom induction principle on concrete syntax. *)

Section InvLemmas.
  Lemma inv_Kt (P : term -> Prop) (t : term) :
    (forall i, P (E_var i)) -> (forall c al, P (E_ctor c al)) -> P t.
  Proof. depelim t ; eauto. Qed.

  Lemma inv_Kal_nil (P : args [] -> Prop) (al : args []) : P E_al_nil -> P al.
  Proof. depelim al ; eauto. Qed.

  Lemma inv_Kal_cons {ty tys} (P : args (ty :: tys) -> Prop) (al : args (ty :: tys)) :
    (forall a al', P (E_al_cons a al')) -> P al.
  Proof. depelim al ; eauto. Qed.

  Lemma inv_Ka_term (P : arg AT_term -> Prop) (a : arg AT_term) :
    (forall t, P (E_aterm t)) -> P a.
  Proof. depelim a ; eauto. Qed.

  Lemma inv_Ka_base {b} (P : arg (AT_base b) -> Prop) (a : arg (AT_base b)) :
    (forall x, P (E_abase b x)) -> P a.
  Proof. depelim a ; eauto. Qed.

  Lemma inv_Ka_bind {ty} (P : arg (AT_bind ty) -> Prop) (a : arg (AT_bind ty)) :
    (forall a', P (E_abind a')) -> P a.
  Proof. depelim a ; eauto. Qed.

End InvLemmas.

(*********************************************************************************)
(** *** Renamings and substitutions. *)
(*********************************************************************************)

(** Rename a term. *)
Equations rename {k} (r : ren) (t : expr k) : expr k :=
rename r (E_var i) := E_var (r i) ;
rename r (E_ctor c al) := E_ctor c (rename r al) ;
rename r E_al_nil := E_al_nil ;
rename r (E_al_cons a al) := E_al_cons (rename r a) (rename r al) ;
rename r (E_abase b x) := E_abase b x ;
rename r (E_aterm t) := E_aterm (rename r t) ;
rename r (E_abind a) := E_abind (rename (up_ren r) a).

(** A substitution on terms is a function [nat -> term] which is applied
    to all free variables. *)
Definition subst := nat -> term.

(** The identity substitution. *)
Definition sid : subst := fun i => E_var i.

(** [sshift] shifts indices by one. *)
Definition sshift : subst :=
  fun i => E_var (S i).

(** Cons a expr with a substitution. *)
Equations scons (t : term) (s : subst) : subst :=
scons t s 0 := t ;
scons t s (S i) := s i.

(** Left to right composition of a substitution with a renaming. *)
Definition srcomp (s : subst) (r : ren) :=
  fun i => rename r (s i).

(** Left to right composition of a renaming with a substitution. *)
Definition rscomp (r : ren) (s : subst) :=
  fun i => s (r i).

(** Lift a substitution through a binder. *)
Definition up_subst (s : subst) : subst :=
  scons (E_var 0) (srcomp s rshift).

(** Apply a substitution to a expr. *)
Equations substitute {k} (s : subst) (t : expr k) : expr k :=
substitute s (E_var i) := s i ;
substitute s (E_ctor c al) := E_ctor c (substitute s al) ;
substitute s E_al_nil := E_al_nil ;
substitute s (E_al_cons a al) := E_al_cons (substitute s a) (substitute s al) ;
substitute s (E_abase b x) := E_abase b x ;
substitute s (E_aterm t) := E_aterm (substitute s t) ;
substitute s (E_abind a) := E_abind (substitute (up_subst s) a).

(** Left to right composition of substitutions. *)
Definition scomp (s1 s2 : subst) : subst :=
  fun i => substitute s2 (s1 i).

(*********************************************************************************)
(** *** Setoid Rewrite Support. *)
(*********************************************************************************)

#[global] Instance up_ren_proper : Proper (eq1 ==> eq1) up_ren.
Proof.
intros r1 r2 Hr i. destruct i ; cbv [rcons up_ren rcomp].
- reflexivity.
- now rewrite Hr.
Qed.

#[global] Instance rcons_proper : Proper (eq ==> eq1 ==> eq1) rcons.
Proof. intros i1 i2 it s1 s2 Hs i. destruct i ; simp rcons. now rewrite Hs. Qed.

#[global] Instance rcomp_proper : Proper (eq1 ==> eq1 ==> eq1) rcomp.
Proof.
intros s1 s2 Hs r1 r2 Hr i. destruct i ; cbv [rcomp].
- now rewrite Hs, Hr.
- now rewrite Hs, Hr.
Qed.

#[global] Instance rename_proper k :
  Proper (eq1 ==> eq ==> eq) (@rename k).
Proof.
intros r1 r2 Hr t _ <-.
induction t in r1, r2, Hr |- * ; simp rename ; f_equal ; auto.
apply IHt. now rewrite Hr.
Qed.

#[global] Instance rscomp_proper : Proper (eq1 ==> eq1 ==> eq1) rscomp.
Proof. intros r1 r2 Hr s1 s2 Hs i. cbv [rscomp]. now rewrite Hs, Hr. Qed.

#[global] Instance srcomp_proper : Proper (eq1 ==> eq1 ==> eq1) srcomp.
Proof. intros s1 s2 Hs r1 r2 Hr i. cbv [srcomp]. now rewrite Hs, Hr. Qed.

#[global] Instance scons_proper : Proper (eq ==> eq1 ==> eq1) scons.
Proof.
intros t1 t2 Ht s1 s2 Hs i.
destruct i ; simp scons. now rewrite Hs.
Qed.

#[global] Instance up_subst_proper : Proper (eq1 ==> eq1) up_subst.
Proof. intros s1 s2 Hs. cbv [up_subst]. now rewrite Hs. Qed.

#[global] Instance substitute_proper k :
  Proper (eq1 ==> eq ==> eq) (@substitute k).
Proof.
intros s1 s2 Hs t ? <-.
induction t in s1, s2, Hs |- * ; simp substitute in * ; f_equal ; auto.
apply IHt. now rewrite Hs.
Qed.

#[global] Instance scomp_proper : Proper (eq1 ==> eq1 ==> eq1) scomp.
Proof. intros s1 s2 Hs r1 r2 Hr i. cbv [scomp]. now rewrite Hs, Hr. Qed.

(*********************************************************************************)
(** *** Properties of renaming and substitution. *)
(*********************************************************************************)

Lemma rid_rcons : rcons 0 rshift =₁ rid.
Proof. intros [|i] ; reflexivity. Qed.

Lemma sid_scons : scons (E_var 0) sshift =₁ sid.
Proof. intros [|i] ; reflexivity. Qed.

Lemma rcomp_rcons_distrib i (r1 r2 : ren) :
  rcomp (rcons i r1) r2 =₁ rcons (r2 i) (rcomp r1 r2).
Proof. intros [|i'] ; reflexivity. Qed.

Lemma scomp_scons_distrib (t : term) (s1 s2 : subst) :
  scomp (scons t s1) s2 =₁ scons (substitute s2 t) (scomp s1 s2).
Proof. intros [|i] ; reflexivity. Qed.

Lemma rshift_rcons i (r : ren) : rcomp rshift (rcons i r) =₁ r.
Proof. reflexivity. Qed.

Lemma sshift_scons (t : term) (s : subst) : scomp sshift (scons t s) =₁ s.
Proof. reflexivity. Qed.

Lemma rcomp_rid_l (r : ren) : rcomp rid r =₁ r.
Proof. reflexivity. Qed.

Lemma rcomp_rid_r (r : ren) : rcomp r rid =₁ r.
Proof. reflexivity. Qed.

Lemma rcomp_assoc (r1 r2 r3 : ren) :
  rcomp (rcomp r1 r2) r3 =₁ rcomp r1 (rcomp r2 r3).
Proof. reflexivity. Qed.

Lemma up_ren_rid : up_ren rid =₁ rid.
Proof. intros [|] ; reflexivity. Qed.

Lemma up_ren_comp (r1 r2 : ren) :
  rcomp (up_ren r1) (up_ren r2) =₁ up_ren (rcomp r1 r2).
Proof. intros [|i] ; reflexivity. Qed.

Lemma ren_rid {k} (t : expr k) : rename rid t = t.
Proof.
induction t ; simp rename ; f_equal ; auto.
now rewrite up_ren_rid, IHt.
Qed.

Lemma ren_ren {k} (t : expr k) (r1 r2 : ren) :
  rename r2 (rename r1 t) = rename (rcomp r1 r2) t.
Proof.
induction t in r1, r2 |- *  ; simp rename ; f_equal ; auto.
now rewrite IHt, up_ren_comp.
Qed.

Lemma ren_subst {k} (t : expr k) (s : subst) (r : ren) :
  rename r (substitute s t) = substitute (srcomp s r) t.
Proof.
induction t in s, r |- * ; simp rename substitute in * ; f_equal ; auto.
rewrite IHt. f_equiv.
intros [|i] ; auto. cbv [up_subst scons srcomp].
rewrite ren_ren, ren_ren. f_equiv.
Qed.

Lemma subst_ren {k} (t : expr k) (r : ren) (s : subst) :
  substitute s (rename r t) = substitute (rscomp r s) t.
Proof.
induction t in r, s |- * ; simp rename substitute in * ; f_equal ; auto.
rewrite IHt. f_equiv. intros [|i] ; reflexivity.
Qed.

Lemma up_subst_comp (s1 s2 : subst) :
  scomp (up_subst s1) (up_subst s2) =₁ up_subst (scomp s1 s2).
Proof.
intros [|i] ; auto. cbv [up_subst scomp]. simp scons. cbv [srcomp].
rewrite ren_subst, subst_ren. f_equiv.
Qed.

Lemma subst_subst {k} (t : expr k) (s1 s2 : subst) :
  substitute s2 (substitute s1 t) = substitute (scomp s1 s2) t.
Proof.
induction t in s1, s2 |- * ; simp substitute ; f_equal ; auto.
rewrite IHt. now rewrite up_subst_comp.
Qed.

Lemma up_subst_sid : up_subst sid =₁ sid.
Proof. intros [|i] ; reflexivity. Qed.

Lemma subst_sid {k} (t : expr k) : substitute sid t = t.
Proof.
induction t ; simp substitute in * ; f_equal ; auto.
rewrite up_subst_sid. assumption.
Qed.

Lemma scomp_sid_l (s : subst) : scomp sid s =₁ s.
Proof. reflexivity. Qed.

Lemma scomp_sid_r (s : subst) : scomp s sid =₁ s.
Proof. intros i. cbv [scomp]. now rewrite subst_sid. Qed.

Lemma scomp_assoc (s1 s2 s3 : subst) :
  scomp (scomp s1 s2) s3 =₁ scomp s1 (scomp s2 s3).
Proof. intros i. cbv [scomp]. now rewrite subst_subst. Qed.

Lemma ren_is_subst {k} (t : expr k) (r : ren) :
  rename r t = substitute (rscomp r E_var) t.
Proof.
induction t in r |- * ; simp rename substitute ; f_equal ; auto.
rewrite IHt. f_equiv. intros [|i] ; reflexivity.
Qed.

Lemma rshift_sshift {k} (t : expr k) :
  rename rshift t = substitute sshift t.
Proof. rewrite ren_is_subst. reflexivity. Qed.

Lemma up_subst_alt (s : subst) :
  up_subst s =₁ scons (E_var 0) (scomp s sshift).
Proof.
simp up_subst. apply scons_proper ; auto.
intros i. cbv [scomp srcomp]. now rewrite rshift_sshift.
Qed.

End WithSignature.
